Parameters:
  GitHubAccessToken:
    Type: String
    NoEcho: true
    Description: "GitHub token required by Amplify to connect the repository."

  GitHubRepositoryURL:
    Type: String
    Description: "URL of the GitHub repository to connect to Amplify."

Resources:
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: AmplifyConsoleServiceRole-Valentin
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AmplifyApp:
    Type: AWS::Amplify::App
    DependsOn: AmplifyServiceRole
    Properties:
      Name: "valentinweyer.com"
      Repository: !Ref GitHubRepositoryURL
      AccessToken: !Ref GitHubAccessToken
      Platform: WEB
      EnableBranchAutoDeletion: false
      BuildSpec: | 
        version: 1
        frontend:
          phases:
            build:
              commands:
                - bash .render-build.sh
          artifacts:
            baseDirectory: public
            files:
              - '**/*'
          cache:
            paths:
              - resources/**/*
      CustomRules:
        - Status: "404-200"
          Target: "/index.html"
          Source: "/<*>"
      CacheConfig:
        Type: AMPLIFY_MANAGED_NO_COOKIES
      JobConfig:
        BuildComputeType: STANDARD_8GB

  AmplifyBranchMain:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      Stage: PRODUCTION
      EnableAutoBuild: true
      EnablePullRequestPreview: false
      EnablePerformanceMode: false
      Framework: Web